//! The single declaration of the IPC surface.
//!
//! Commands and events are registered **here and nowhere else**: the same
//! [`tauri_specta::Builder`] feeds the running application
//! ([`crate::run`]) and the generator (`src/bin/gen_ipc.rs`). One list, so a
//! command cannot be reachable at runtime while absent from the TypeScript
//! bindings — the exact drift ADR 0003 set out to close.

use std::path::Path;

use specta_typescript::Typescript;
use tauri_specta::{collect_commands, collect_events, Builder, ErrorHandlingMode};

/// Marker every generated file carries.
///
/// `scripts/check-ipc-types.sh` looks for it to tell a generated file from a
/// hand-written one, and refuses the second in `ui/src/ipc/generated/`.
const HEADER: &str = "// @generated by `cargo run --bin gen_ipc` — do not edit.\n\
                      // Source of truth: src-tauri/src/ipc.rs and the DTOs it references.\n\
                      // Regenerate with `just ipc-check`; CI step 4 fails on an uncommitted diff.\n";

/// Builds the IPC surface: commands, events, error handling.
pub(crate) fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            crate::commands::config::config_get,
            crate::commands::config::config_set,
            crate::commands::session::session_create,
            crate::commands::session::session_update,
            crate::commands::session::session_delete,
            crate::commands::session::session_list,
            crate::commands::session::session_bind,
            crate::commands::session::session_unbind,
            crate::commands::session::session_status,
        ])
        .events(collect_events![
            crate::events::ErrorNotify,
            crate::events::SessionsState
        ])
        // A command that fails must produce a *value* on the TypeScript side,
        // not a thrown exception: `Result<T, ErrorDto>` forces the caller to
        // handle the error, whereas a `throw` is silently ignorable.
        .error_handling(ErrorHandlingMode::Result)
}

/// Writes the TypeScript bindings to `path`.
///
/// # Errors
///
/// Returns an error if the target directory cannot be created or the file
/// cannot be written.
pub(crate) fn export(path: &Path) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Every numeric field of the contract is a `u16`/`u32`, which
    // `specta-typescript` maps to `number`. Should a future DTO need a 64-bit
    // integer, it goes over the bridge as a string rather than as a `BigInt`:
    // JSON does not carry one, and `JSON.stringify` throws on it.
    builder().export(Typescript::default().header(HEADER), path)?;

    Ok(())
}
